apiVersion: v1
kind: Config
preferences: {}

# Define the cluster
clusters:
- cluster:
    certificate-authority-data: $CERTIFICATE
    server: https://$KUBERNETES_API_ENDPOINT
  name: $CLUSTER_NAME

# Define the user
users:
- name: $NAMESPACE-user
  user:
    as-user-extra: {}
    client-key-data: $CERTIFICATE
    token: $TOKEN

# Define the context: linking a user to a cluster
contexts:
- context:
    cluster: $CLUSTER_NAME
    namespace: $NAMESPACE
    user: $NAMESPACE-user
  name: $NAMESPACE

# Define current context
current-context: $NAMESPACE
